/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { useState, useMemo } from 'react';
import { 
  ResponsiveContainer, 
  AreaChart, 
  Area, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  BarChart, 
  Bar, 
  XAxis as BarXAxis,
  YAxis as BarYAxis,
  Cell
} from 'recharts';
import { 
  TrendingUp, 
  TrendingDown, 
  Activity, 
  Clock, 
  Target, 
  Briefcase, 
  Sliders, 
  Zap, 
  BarChart3, 
  Info, 
  Check, 
  Layers, 
  Search,
  Scale,
  Shield,
  Percent,
  LineChart as LineIcon,
  BookOpen,
  PieChart,
  DollarSign
} from 'lucide-react';
import { motion } from 'motion/react';
import { Trade } from '../types.ts';

interface MarketAnalysisDashboardProps {
  trades: Trade[];
}

interface AssetDetail {
  symbol: string;
  name: string;
  qty: number;
  avgCost: number;
  marketPrice: number;
  returnVal: string;
  returnPnl: number;
  weight: string;
  dividend: string;
  volatility: string;
  riskContrib: string;
  fiftyTwoWeek: string;
  consensus: string;
  drivers: string[];
  thesis: string;
  marketCap: string;
  peRatio: string;
  psRatio: string;
  profitMargin: string;
  debtEquity: string;
  beta: string;
  eps: string;
}

const FINANCIAL_METRICS_INFO: Record<string, {
  definition: string;
  average: string;
  alert: string;
}> = {
  'Market Cap': {
    definition: 'Aggregate market value of a company\'s outstanding shares. Represents the total equity size of the enterprise.',
    average: 'Mega-cap benchmark: >$200B. Large-cap baseline: >$10B.',
    alert: '✓ High liquidity institutional tier.'
  },
  'P/E Ratio': {
    definition: 'Price-to-Earnings multiple. Measures the price paid for each unit of annual net income generated by the firm.',
    average: 'Historical S&P 500 average: 15.0x – 18.0x.',
    alert: '>25.0x represents growth premium pricing.'
  },
  'P/S Ratio': {
    definition: 'Price-to-Sales multiple. Evaluates equity valuation relative to gross revenue turnover, bypassing earnings noise.',
    average: 'Software average: 8.0x – 12.0x. S&P 500 median: 2.5x.',
    alert: '>10.0x demands aggressive revenue scale-up.'
  },
  'Debt / Equity': {
    definition: 'Total liabilities divided by shareholder equity. Quantifies capital structure leverage and balance sheet solvency risks.',
    average: 'Healthy growth average: <0.8 (Tech) or <1.5 (Industrial).',
    alert: '>2.0 signals substantial debt service stress.'
  },
  'Profit Margin': {
    definition: 'Net profit divided by total revenues. Measures absolute bottom-line pricing power and operational efficiency.',
    average: 'S&P 500 historical average profit margin: ~10% – 12%.',
    alert: '>20% confirms high-grade competitive moats.'
  },
  'Beta': {
    definition: 'Systemic volatility covariance coefficient relative to the S&P 500 (1.00). Quantifies systemic market risk exposure.',
    average: 'Market baseline: 1.00. High volatility: >1.30.',
    alert: '<1.00 offers systematic portfolio volatility dampening.'
  },
  'EPS (LTM)': {
    definition: 'Earnings Per Share. Net income divided by total outstanding diluted shares over trailing 12 months.',
    average: 'Varies by security size. Index average base: ~$220.',
    alert: 'Consistent positive growth validates earnings robustness.'
  }
};

// Full Holdings Ledger Detail Map
const HOLDINGS_DETAILS: Record<string, AssetDetail> = {
  AAPL: {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    qty: 25,
    avgCost: 280.00,
    marketPrice: 307.00,
    returnVal: '+9.6%',
    returnPnl: 675.00,
    weight: '18%',
    dividend: '0.46%',
    volatility: 'Medium',
    riskContrib: '12%',
    fiftyTwoWeek: 'Near Highs',
    consensus: 'Moderate Buy',
    drivers: ['AI Infrastructure', 'Services Growth', 'Share Buybacks', 'Institutional Accumulation'],
    thesis: 'Apple continues benefiting from robust high-margin services revenue growth and an impending AI-driven device upgrade cycle. Balance sheet fortress with aggressive stock buyback yields supports current premium valuations.',
    marketCap: '$3.45T',
    peRatio: '31.4',
    psRatio: '8.9',
    profitMargin: '26.3%',
    debtEquity: '1.43',
    beta: '1.01',
    eps: '$6.16'
  },
  NVDA: {
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    qty: 12,
    avgCost: 130.00,
    marketPrice: 170.00,
    returnVal: '+30.7%',
    returnPnl: 480.00,
    weight: '16%',
    dividend: '0.02%',
    volatility: 'High',
    riskContrib: '24%',
    fiftyTwoWeek: 'All-Time Highs',
    consensus: 'Strong Buy',
    drivers: ['AI Infrastructure', 'Datacenter Dominance', 'Next-Gen Chips', 'Institutional Accumulation'],
    thesis: 'Uncontested market share in compute fabrics with robust hyper-scaler demand pipelines. While valuations remain rich, sequential operating margins continue to surprise on the upside, validating secular structural growth.',
    marketCap: '$3.10T',
    peRatio: '68.2',
    psRatio: '24.5',
    profitMargin: '53.2%',
    debtEquity: '0.17',
    beta: '1.85',
    eps: '$2.82'
  },
  SPY: {
    symbol: 'SPY',
    name: 'SPDR S&P 500 ETF Trust',
    qty: 30,
    avgCost: 550.00,
    marketPrice: 575.00,
    returnVal: '+4.5%',
    returnPnl: 750.00,
    weight: '20%',
    dividend: '1.32%',
    volatility: 'Low',
    riskContrib: '8%',
    fiftyTwoWeek: 'Near Highs',
    consensus: 'Buy',
    drivers: ['Broad Diversification', 'Liquid Options', 'Sovereign Security', 'Institutional Accumulation'],
    thesis: 'Serves as the absolute structural anchor for systemic beta tracking. Satisfies core compliance metrics while buffering higher-volatility individual equity spikes.',
    marketCap: '$558B',
    peRatio: '24.8',
    psRatio: '3.1',
    profitMargin: '11.5%',
    debtEquity: '0.85',
    beta: '1.00',
    eps: '$23.18'
  },
  MSFT: {
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    qty: 15,
    avgCost: 410.00,
    marketPrice: 422.00,
    returnVal: '+2.9%',
    returnPnl: 180.00,
    weight: '15%',
    dividend: '0.71%',
    volatility: 'Low',
    riskContrib: '11%',
    fiftyTwoWeek: 'Mid-Range',
    consensus: 'Strong Buy',
    drivers: ['AI Infrastructure', 'Cloud Scalability', 'Enterprise Moats', 'Institutional Accumulation'],
    thesis: 'Enterprise AI commercialization via Copilot and Azure is scaling ahead of projections. Operating margins maintain a robust floor due to sticky long-term software subscriptions and sovereign cloud migrations.',
    marketCap: '$3.15T',
    peRatio: '34.7',
    psRatio: '12.1',
    profitMargin: '35.4%',
    debtEquity: '0.42',
    beta: '0.90',
    eps: '$11.80'
  },
  GOOGL: {
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    qty: 20,
    avgCost: 175.00,
    marketPrice: 166.00,
    returnVal: '-5.1%',
    returnPnl: -180.00,
    weight: '10%',
    dividend: '0.48%',
    volatility: 'Medium',
    riskContrib: '9%',
    fiftyTwoWeek: 'Consolidating',
    consensus: 'Buy',
    drivers: ['Search Resiliency', 'YouTube Monetization', 'AI Search Integration', 'Institutional Accumulation'],
    thesis: 'Near-term valuation discount reflects legal headwind concerns. However, core search revenue structures remain extremely resilient with cloud division reaching structural profitability scale.',
    marketCap: '$2.05T',
    peRatio: '22.1',
    psRatio: '6.4',
    profitMargin: '25.9%',
    debtEquity: '0.11',
    beta: '1.12',
    eps: '$6.97'
  },
  AMZN: {
    symbol: 'AMZN',
    name: 'Amazon.com Inc.',
    qty: 18,
    avgCost: 180.00,
    marketPrice: 189.00,
    returnVal: '+5.0%',
    returnPnl: 162.00,
    weight: '12%',
    dividend: '0.00%',
    volatility: 'Medium',
    riskContrib: '10%',
    fiftyTwoWeek: 'Near Highs',
    consensus: 'Strong Buy',
    drivers: ['Cloud Acceleration', 'Retail Efficiency', 'Advertising Network', 'Institutional Accumulation'],
    thesis: 'AWS segment is showing clear re-acceleration alongside strong high-margin advertising momentum. Fulfills fundamental requirements for high-margin infrastructure growth profiles.',
    marketCap: '$1.98T',
    peRatio: '40.5',
    psRatio: '3.2',
    profitMargin: '6.4%',
    debtEquity: '0.55',
    beta: '1.15',
    eps: '$4.18'
  },
  Cash: {
    symbol: 'Cash',
    name: 'USD Liquidity Reserves',
    qty: 9200,
    avgCost: 1.00,
    marketPrice: 1.00,
    returnVal: '--',
    returnPnl: 0,
    weight: '9%',
    dividend: '5.20%',
    volatility: 'None',
    riskContrib: '0%',
    fiftyTwoWeek: 'Stable',
    consensus: 'Hold',
    drivers: ['Sovereign Security', 'Yield Capture', 'Slippage Defense', 'Institutional Accumulation'],
    thesis: 'Maintained strictly as dry powder for systemic liquidity risk defense and to capture high risk-free yields. Satisfies high-grade compliance liquidity ratios.',
    marketCap: '--',
    peRatio: '--',
    psRatio: '--',
    profitMargin: '--',
    debtEquity: '--',
    beta: '0.00',
    eps: '--'
  }
};;

// Generates simulated historical curves based on timeframe selections and toggled benchmarks
const generatePerformanceData = (timeframe: string, benchmarks: Record<string, boolean>) => {
  let length = 30;
  let startValue = 100000;
  let spxStart = 5000;
  let ndxStart = 17000;

  switch (timeframe) {
    case '1W':
      length = 7;
      break;
    case '1M':
      length = 30;
      break;
    case '3M':
      length = 90;
      break;
    case 'YTD':
      length = 180;
      break;
    case '1Y':
      length = 250;
      break;
    case 'ALL':
      length = 500;
      break;
  }

  const data = [];
  const baseDate = new Date('2026-07-03T11:00:00Z');

  for (let i = 0; i < length; i++) {
    const dayOffset = length - 1 - i;
    const date = new Date(baseDate.getTime() - dayOffset * 24 * 60 * 60 * 1000);
    const dateStr = date.toLocaleDateString(undefined, { month: 'short', day: 'numeric' });

    // Seed-based random walk so that the shape remains beautiful, consistent, and organic
    const t = i / length;
    const sineFactor = Math.sin(t * Math.PI * 2.5) * 8000;
    const noiseFactor = Math.sin(i * 0.4) * 1200 + Math.cos(i * 0.9) * 800;
    const upwardTrend = t * 14000;

    // Base value calculations
    const portfolioVal = startValue + upwardTrend + sineFactor + noiseFactor;
    const spxVal = spxStart * (portfolioVal / startValue * 0.95 + Math.sin(i * 0.1) * 0.02);
    const ndxVal = ndxStart * (portfolioVal / startValue * 1.05 + Math.cos(i * 0.1) * 0.04);
    const cashContrib = startValue + (i > length / 2 ? 8000 : 0) + (i > length * 0.8 ? 5000 : 0);

    const record: Record<string, any> = {
      date: dateStr,
      portfolio: Number(portfolioVal.toFixed(2))
    };

    if (benchmarks['S&P 500']) {
      record.spx = Number((spxVal * (startValue / spxStart)).toFixed(2)); // normalized to portfolio starting scale
    }
    if (benchmarks['Nasdaq']) {
      record.nasdaq = Number((ndxVal * (startValue / ndxStart)).toFixed(2)); // normalized to portfolio starting scale
    }
    if (benchmarks['Cash Contributions']) {
      record.cash = Number(cashContrib.toFixed(2));
    }

    data.push(record);
  }

  return data;
};

export default function MarketAnalysisDashboard({ trades }: MarketAnalysisDashboardProps) {
  // Navigation & Toggle States
  const [activeTimeframe, setActiveTimeframe] = useState<'1W' | '1M' | '3M' | 'YTD' | '1Y' | 'ALL'>('3M');
  const [selectedAssetKey, setSelectedAssetKey] = useState<string>('AAPL');
  const [assetTab, setAssetTab] = useState<'FINANCIALS' | 'RISK' | 'THESIS'>('FINANCIALS');
  
  // Benchmark Overlays
  const [benchmarks, setBenchmarks] = useState<Record<string, boolean>>({
    'Portfolio Value': true,
    'S&P 500': true,
    'Nasdaq': false,
    'Cash Contributions': false
  });

  const toggleBenchmark = (b: string) => {
    if (b === 'Portfolio Value') return; // Always keep the primary active
    setBenchmarks(prev => ({
      ...prev,
      [b]: !prev[b]
    }));
  };

  // Generate curves based on timeframe & benchmarks
  const chartData = useMemo(() => {
    return generatePerformanceData(activeTimeframe, benchmarks);
  }, [activeTimeframe, benchmarks]);

  // Selected asset detail
  const selectedAsset = useMemo(() => {
    return HOLDINGS_DETAILS[selectedAssetKey] || HOLDINGS_DETAILS['AAPL'];
  }, [selectedAssetKey]);

  return (
    <div id="intelligence-terminal" className="space-y-6">
      
      {/* HEADER SECTION WITH TOP-RIGHT SYSTEM INDICATORS */}
      <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-4 border-b border-white/5 pb-5">
        <div className="text-left">
          <div className="flex items-center gap-2.5">
            <div className="p-1.5 bg-emerald-500/10 rounded-lg border border-emerald-500/20 text-emerald-400">
              <Shield className="w-5 h-5" />
            </div>
            <div>
              <h1 className="text-lg font-black text-white uppercase tracking-wider font-mono">
                INTELLIGENCE TERMINAL
              </h1>
              <p className="text-[10.5px] text-white/40 font-mono">
                Institutional research, portfolio diagnostics, risk decomposition, and market intelligence.
              </p>
            </div>
          </div>
        </div>

        {/* System Indicators Panel */}
        <div className="flex flex-wrap items-center gap-4 text-[10px] font-mono">
          <div className="bg-white/[0.02] border border-white/5 px-3 py-1.5 rounded-lg flex items-center gap-2">
            <span className="text-white/30 uppercase tracking-wider text-[8.5px]">Market Regime:</span>
            <span className="text-emerald-400 font-bold flex items-center gap-1.5">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse"></span>
              Risk-On
            </span>
          </div>

          <div className="bg-white/[0.02] border border-white/5 px-3 py-1.5 rounded-lg flex items-center gap-2">
            <span className="text-white/30 uppercase tracking-wider text-[8.5px]">Portfolio Health:</span>
            <span className="text-indigo-400 font-black">91 / 100</span>
          </div>


        </div>
      </div>

      {/* SECTION 1: PORTFOLIO INTELLIGENCE OVERVIEW */}
      <div className="grid grid-cols-2 lg:grid-cols-6 gap-3">
        
        {/* Card 1: Portfolio Return */}
        <motion.div 
          whileHover={{ y: -2, borderColor: 'rgba(16, 185, 129, 0.25)', boxShadow: '0 4px 20px -2px rgba(16, 185, 129, 0.08)' }}
          transition={{ type: 'spring', stiffness: 400, damping: 25 }}
          className="bg-[#080808] p-3.5 rounded-xl border border-white/5 space-y-1 text-left relative overflow-hidden group transition-colors duration-200"
        >
          <div className="absolute top-0 left-0 w-1 h-full bg-emerald-500/50"></div>
          <span className="text-[9px] font-mono text-white/40 uppercase tracking-wider block">Portfolio Return</span>
          <span className="text-lg font-black font-mono block text-emerald-400 mt-1">
            +$4,670.12
          </span>
          <span className="text-[8.5px] font-mono text-emerald-400/80 block">
            +18.4% YTD
          </span>
        </motion.div>

        {/* Card 2: Diversification Score */}
        <motion.div 
          whileHover={{ y: -2, borderColor: 'rgba(99, 102, 241, 0.25)', boxShadow: '0 4px 20px -2px rgba(99, 102, 241, 0.08)' }}
          transition={{ type: 'spring', stiffness: 400, damping: 25 }}
          className="bg-[#080808] p-3.5 rounded-xl border border-white/5 space-y-1 text-left relative overflow-hidden group transition-colors duration-200"
        >
          <div className="absolute top-0 left-0 w-1 h-full bg-indigo-500/50"></div>
          <span className="text-[9px] font-mono text-white/40 uppercase tracking-wider block">Diversification Score</span>
          <span className="text-lg font-black font-mono block text-white mt-1">
            84 / 100
          </span>
          <span className="text-[8.5px] font-mono text-indigo-400 block font-bold uppercase tracking-wide">
            Well Diversified
          </span>
        </motion.div>

        {/* Card 3: Portfolio Risk */}
        <motion.div 
          whileHover={{ y: -2, borderColor: 'rgba(245, 158, 11, 0.25)', boxShadow: '0 4px 20px -2px rgba(245, 158, 11, 0.08)' }}
          transition={{ type: 'spring', stiffness: 400, damping: 25 }}
          className="bg-[#080808] p-3.5 rounded-xl border border-white/5 space-y-1 text-left relative overflow-hidden group transition-colors duration-200"
        >
          <div className="absolute top-0 left-0 w-1 h-full bg-amber-500/50"></div>
          <span className="text-[9px] font-mono text-white/40 uppercase tracking-wider block">Portfolio Risk</span>
          <span className="text-lg font-black font-mono block text-amber-400 mt-1">
            Moderate
          </span>
          <span className="text-[8.5px] font-mono text-white/30 block">
            Beta: 1.08
          </span>
        </motion.div>

        {/* Card 4: Concentration Exposure */}
        <motion.div 
          whileHover={{ y: -2, borderColor: 'rgba(236, 72, 153, 0.25)', boxShadow: '0 4px 20px -2px rgba(236, 72, 153, 0.08)' }}
          transition={{ type: 'spring', stiffness: 400, damping: 25 }}
          className="bg-[#080808] p-3.5 rounded-xl border border-white/5 space-y-1 text-left relative overflow-hidden group transition-colors duration-200"
        >
          <div className="absolute top-0 left-0 w-1 h-full bg-pink-500/50"></div>
          <span className="text-[9px] font-mono text-white/40 uppercase tracking-wider block">Concentration Exposure</span>
          <span className="text-lg font-black font-mono block text-white mt-1">
            34%
          </span>
          <span className="text-[8.5px] font-mono text-pink-400 block font-bold uppercase">
            Technology Sector
          </span>
        </motion.div>

        {/* Card 5: Dividend Yield */}
        <motion.div 
          whileHover={{ y: -2, borderColor: 'rgba(20, 184, 166, 0.25)', boxShadow: '0 4px 20px -2px rgba(20, 184, 166, 0.08)' }}
          transition={{ type: 'spring', stiffness: 400, damping: 25 }}
          className="bg-[#080808] p-3.5 rounded-xl border border-white/5 space-y-1 text-left relative overflow-hidden group transition-colors duration-200"
        >
          <div className="absolute top-0 left-0 w-1 h-full bg-teal-500/50"></div>
          <span className="text-[9px] font-mono text-white/40 uppercase tracking-wider block">Dividend Yield</span>
          <span className="text-lg font-black font-mono block text-teal-400 mt-1">
            2.9%
          </span>
          <span className="text-[8.5px] font-mono text-white/30 block">
            Est. Annual Income
          </span>
        </motion.div>

        {/* Card 6: Downside Stress */}
        <motion.div 
          whileHover={{ y: -2, borderColor: 'rgba(239, 68, 68, 0.25)', boxShadow: '0 4px 20px -2px rgba(239, 68, 68, 0.08)' }}
          transition={{ type: 'spring', stiffness: 400, damping: 25 }}
          className="bg-[#080808] p-3.5 rounded-xl border border-white/5 space-y-1 text-left relative overflow-hidden group transition-colors duration-200"
        >
          <div className="absolute top-0 left-0 w-1 h-full bg-red-500/50"></div>
          <span className="text-[9px] font-mono text-white/40 uppercase tracking-wider block">Downside Stress</span>
          <span className="text-lg font-black font-mono block text-red-400 mt-1">
            -11%
          </span>
          <span className="text-[8.5px] font-mono text-red-400/80 block uppercase tracking-wide">
            Simulated Crash
          </span>
        </motion.div>
      </div>

      {/* SECTION 2: PORTFOLIO VALUE CURVE */}
      <motion.div 
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, ease: 'easeOut' }}
        className="bg-[#080808] border border-white/5 rounded-xl p-4 md:p-6 text-left"
      >
        <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-4 border-b border-white/5 pb-4 mb-4">
          <div>
            <h3 className="text-sm font-black text-white uppercase tracking-wider font-mono flex items-center gap-2">
              <Activity className="w-4 h-4 text-indigo-400" /> Portfolio Value & Performance
            </h3>
            <p className="text-[10px] text-white/40 font-mono">
              Sovereign investment value over time overlaid against benchmark indices.
            </p>
          </div>

          <div className="flex flex-col sm:flex-row items-start sm:items-center gap-4">
            
            {/* Timeframe selector */}
            <div className="flex items-center bg-[#0d0d12] border border-white/10 rounded-lg p-0.5 font-mono text-[9.5px]">
              {(['1W', '1M', '3M', 'YTD', '1Y', 'ALL'] as const).map((tf) => (
                <button
                  key={tf}
                  onClick={() => setActiveTimeframe(tf)}
                  className={`px-2 py-1 rounded font-bold transition-all cursor-pointer ${
                    activeTimeframe === tf 
                      ? 'bg-indigo-600 text-white' 
                      : 'text-white/45 hover:text-white/95'
                  }`}
                >
                  {tf}
                </button>
              ))}
            </div>

            {/* Benchmark toggles */}
            <div className="flex flex-wrap items-center gap-1.5 text-[9px] font-mono">
              {Object.keys(benchmarks).map((b) => {
                const isActive = benchmarks[b];
                return (
                  <button
                    key={b}
                    onClick={() => toggleBenchmark(b)}
                    className={`px-2.5 py-1 rounded-md border transition-all cursor-pointer font-bold uppercase tracking-wider ${
                      isActive 
                        ? b === 'Portfolio Value' 
                          ? 'bg-indigo-500/15 border-indigo-500/35 text-indigo-300'
                          : b === 'S&P 500'
                            ? 'bg-emerald-500/15 border-emerald-500/35 text-emerald-300'
                            : b === 'Nasdaq'
                              ? 'bg-pink-500/15 border-pink-500/35 text-pink-300'
                              : 'bg-amber-500/15 border-amber-500/35 text-amber-300'
                        : 'bg-white/[0.01] border-white/5 text-white/30 hover:border-white/10'
                    }`}
                  >
                    {b}
                  </button>
                );
              })}
            </div>

          </div>
        </div>

        {/* Recharts Area Chart */}
        <div className="h-[280px] md:h-[350px] w-full mt-2 select-none relative overflow-hidden">
          <motion.div
            key={`${activeTimeframe}-${Object.entries(benchmarks).filter(([_, v]) => v).map(([k]) => k).join(',')}`}
            initial={{ opacity: 0.1, y: 5 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.45, ease: [0.16, 1, 0.3, 1] }}
            className="w-full h-full"
          >
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart
                data={chartData}
                margin={{ top: 10, right: 15, left: 15, bottom: 0 }}
              >
                <defs>
                  <linearGradient id="pValueGrad" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#4f46e5" stopOpacity={0.25} />
                    <stop offset="95%" stopColor="#4f46e5" stopOpacity={0.0} />
                  </linearGradient>
                  <linearGradient id="spxGrad" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#10b981" stopOpacity={0.05} />
                    <stop offset="95%" stopColor="#10b981" stopOpacity={0.0} />
                  </linearGradient>
                  <linearGradient id="ndxGrad" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#ec4899" stopOpacity={0.05} />
                    <stop offset="95%" stopColor="#ec4899" stopOpacity={0.0} />
                  </linearGradient>
                </defs>
                <CartesianGrid stroke="#ffffff" strokeOpacity={0.03} strokeDasharray="3 3" />
                <XAxis 
                  dataKey="date" 
                  stroke="#ffffff" 
                  strokeOpacity={0.15} 
                  tick={{ fill: 'rgba(255,255,255,0.35)', fontSize: 9.5, fontFamily: 'monospace' }}
                  dy={6}
                />
                <YAxis 
                  stroke="#ffffff" 
                  strokeOpacity={0.15} 
                  tick={{ fill: 'rgba(255,255,255,0.35)', fontSize: 9.5, fontFamily: 'monospace' }}
                  domain={['dataMin - 1000', 'dataMax + 1000']}
                  tickFormatter={(val) => `$${(val / 1000).toFixed(0)}k`}
                  dx={-6}
                />
                <Tooltip
                  cursor={{ stroke: 'rgba(255, 255, 255, 0.15)', strokeWidth: 1 }}
                  content={({ active, payload }) => {
                    if (active && payload && payload.length) {
                      return (
                        <div className="bg-[#0a0a0f] border border-white/10 p-3 rounded-lg shadow-2xl font-mono text-[10px] space-y-1.5 text-left">
                          <div className="border-b border-white/5 pb-1 text-white/50 font-bold">
                            {payload[0].payload.date}
                          </div>
                          {payload.map((item, index) => {
                            let color = '#818cf8';
                            let label = 'Portfolio Value';
                            if (item.name === 'spx') { color = '#34d399'; label = 'S&P 500 (Normalized)'; }
                            else if (item.name === 'nasdaq') { color = '#f472b6'; label = 'Nasdaq (Normalized)'; }
                            else if (item.name === 'cash') { color = '#fbbf24'; label = 'Cash Contrib.'; }

                            return (
                              <div key={index} className="flex items-center justify-between gap-5">
                                <span style={{ color }} className="font-bold uppercase text-[9px]">{label}:</span>
                                <strong className="text-white text-[10.5px]">${Number(item.value).toLocaleString()}</strong>
                              </div>
                            );
                          })}
                        </div>
                      );
                    }
                    return null;
                  }}
                />
                
                {/* Primary Portfolio Value Area */}
                <Area
                  name="portfolio"
                  type="monotone"
                  dataKey="portfolio"
                  stroke="#4f46e5"
                  strokeWidth={2.5}
                  fillOpacity={1}
                  fill="url(#pValueGrad)"
                  activeDot={{ r: 5, stroke: '#818cf8', strokeWidth: 1, fill: '#080808' }}
                  isAnimationActive={true}
                  animationDuration={450}
                  animationEasing="ease-out"
                />

                {/* S&P 500 normalized */}
                {benchmarks['S&P 500'] && (
                  <Area
                    name="spx"
                    type="monotone"
                    dataKey="spx"
                    stroke="#10b981"
                    strokeWidth={1.5}
                    strokeDasharray="4 4"
                    fillOpacity={1}
                    fill="url(#spxGrad)"
                    activeDot={{ r: 4, stroke: '#34d399', strokeWidth: 1, fill: '#080808' }}
                    isAnimationActive={true}
                    animationDuration={450}
                    animationEasing="ease-out"
                  />
                )}

                {/* Nasdaq normalized */}
                {benchmarks['Nasdaq'] && (
                  <Area
                    name="nasdaq"
                    type="monotone"
                    dataKey="nasdaq"
                    stroke="#ec4899"
                    strokeWidth={1.5}
                    strokeDasharray="4 4"
                    fillOpacity={1}
                    fill="url(#ndxGrad)"
                    activeDot={{ r: 4, stroke: '#f472b6', strokeWidth: 1, fill: '#080808' }}
                    isAnimationActive={true}
                    animationDuration={450}
                    animationEasing="ease-out"
                  />
                )}

                {/* Cash Contributions */}
                {benchmarks['Cash Contributions'] && (
                  <Area
                    name="cash"
                    type="step"
                    dataKey="cash"
                    stroke="#fbbf24"
                    strokeWidth={1.5}
                    fillOpacity={0}
                    activeDot={{ r: 4, stroke: '#fbbf24', strokeWidth: 1, fill: '#080808' }}
                    isAnimationActive={true}
                    animationDuration={450}
                    animationEasing="ease-out"
                  />
                )}
              </AreaChart>
            </ResponsiveContainer>
          </motion.div>
        </div>
      </motion.div>

      {/* SECTION 3: PERFORMANCE ATTRIBUTION & SECTION 4: MARKET OPPORTUNITY MAP */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        
        {/* SECTION 3: CONTRIBUTION TO RETURNS */}
        <div className="bg-[#080808] border border-white/5 rounded-xl p-4 text-left">
          <div className="border-b border-white/5 pb-3 mb-3">
            <h4 className="text-xs font-black text-white uppercase tracking-wider font-mono flex items-center gap-1.5">
              <PieChart className="w-4 h-4 text-indigo-400" /> Contribution To Returns
            </h4>
            <p className="text-[10px] text-white/40 font-mono">
              Individual asset allocations ranked by absolute returns contribution.
            </p>
          </div>

          <div className="h-[210px] w-full flex flex-col justify-center space-y-3 font-mono text-[10.5px]">
            {[
              { asset: 'NVDA', pnl: 1890, pct: 100 },
              { asset: 'AAPL', pnl: 870, pct: 46 },
              { asset: 'SPY', pnl: 640, pct: 34 },
              { asset: 'GOOGL', pnl: -190, pct: -10 },
              { asset: 'Cash', pnl: 0, pct: 0 }
            ].map((item, i) => {
              const isPositive = item.pnl > 0;
              const isZero = item.pnl === 0;
              return (
                <div key={i} className="space-y-1">
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-white text-[10px]">{item.asset}</span>
                    <span className={`font-bold ${isPositive ? 'text-emerald-400' : isZero ? 'text-white/40' : 'text-pink-400'}`}>
                      {isPositive ? '+$' : isZero ? '$' : '-$'}{Math.abs(item.pnl).toLocaleString()}
                    </span>
                  </div>
                  <div className="h-2 bg-white/[0.02] rounded-full overflow-hidden flex items-center">
                    {isPositive ? (
                      <div 
                        style={{ width: `${item.pct}%` }} 
                        className="h-full bg-emerald-500/30 border-r border-emerald-400/50"
                      ></div>
                    ) : isZero ? (
                      <div className="w-0.5 h-full bg-white/20"></div>
                    ) : (
                      <div 
                        style={{ width: `${Math.abs(item.pct)}%` }} 
                        className="h-full bg-pink-500/30 border-r border-pink-400/50"
                      ></div>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* SECTION 4: MARKET OPPORTUNITY MAP */}
        <div className="bg-[#080808] border border-white/5 rounded-xl p-4 text-left">
          <div className="border-b border-white/5 pb-3 mb-3">
            <h4 className="text-xs font-black text-white uppercase tracking-wider font-mono flex items-center gap-1.5">
              <Zap className="w-4 h-4 text-emerald-400" /> Market Opportunity Map
            </h4>
            <p className="text-[10px] text-white/40 font-mono">
              Quantitative asset score card based on proprietary machine intelligence.
            </p>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-[10px] font-mono text-left border-collapse">
              <thead className="text-white/35 uppercase border-b border-white/10 text-[9px]">
                <tr>
                  <th className="pb-2.5">Asset</th>
                  <th className="pb-2.5 text-center">Momentum</th>
                  <th className="pb-2.5 text-center">Valuation</th>
                  <th className="pb-2.5 text-right">AI Score</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/[0.04]">
                {[
                  { sym: 'NVDA', mom: 'Strong', val: 'Expensive', score: 82, color: 'text-indigo-400' },
                  { sym: 'AAPL', mom: 'Moderate', val: 'Fair', score: 88, color: 'text-emerald-400' },
                  { sym: 'AMZN', mom: 'Strong', val: 'Fair', score: 91, color: 'text-emerald-400' },
                  { sym: 'SPY', mom: 'Neutral', val: 'Fair', score: 80, color: 'text-indigo-400' }
                ].map((row, idx) => (
                  <tr key={idx} className="hover:bg-white/[0.02] transition-colors">
                    <td className="py-2.5 text-white font-bold">{row.sym}</td>
                    <td className="py-2.5 text-center">
                      <span className={`px-1.5 py-0.5 rounded text-[8.5px] font-bold ${
                        row.mom === 'Strong' 
                          ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20' 
                          : 'bg-indigo-500/10 text-indigo-400 border border-indigo-500/20'
                      }`}>
                        {row.mom}
                      </span>
                    </td>
                    <td className="py-2.5 text-center">
                      <span className={`px-1.5 py-0.5 rounded text-[8.5px] font-bold ${
                        row.val === 'Expensive' 
                          ? 'bg-amber-500/10 text-amber-400 border border-amber-500/20' 
                          : 'bg-white/5 text-white/50 border border-white/10'
                      }`}>
                        {row.val}
                      </span>
                    </td>
                    <td className="py-2.5 text-right text-white font-bold">
                      <span className={`px-1.5 py-0.5 rounded text-[9.5px] ${row.color} bg-white/[0.02] border border-white/5 font-bold`}>
                        {row.score}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* SECTION 5: HOLDINGS INTELLIGENCE LEDGER (Left) & ASSET INTELLIGENCE CARD (Right) */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-4">
        
        {/* Holdings Ledger Table */}
        <div className="lg:col-span-8 bg-[#080808] border border-white/5 rounded-xl p-4 text-left flex flex-col justify-between">
          <div>
            <div className="border-b border-white/5 pb-3 mb-3 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
              <div>
                <h4 className="text-xs font-black text-white uppercase tracking-wider font-mono">
                  Holdings Ledger
                </h4>
                <p className="text-[10px] text-white/40 font-mono">
                  Active asset weights, acquisition prices, and immediate market return summaries.
                </p>
              </div>
            </div>

            <div className="overflow-x-auto border border-white/5 rounded-lg">
              <table className="w-full text-[10.5px] font-mono text-left border-collapse">
                <thead className="bg-[#0b0b0f] text-white/40 sticky top-0 uppercase tracking-wider text-[9px] border-b border-b-white/10">
                  <tr>
                    <th className="p-2.5">Asset</th>
                    <th className="p-2.5 text-right">Quantity</th>
                    <th className="p-2.5 text-right">Avg Cost</th>
                    <th className="p-2.5 text-right">Market Price</th>
                    <th className="p-2.5 text-right">Return</th>
                    <th className="p-2.5 text-right">Portfolio Weight</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/[0.04] bg-[#020202]/30">
                  {Object.values(HOLDINGS_DETAILS).map((h) => {
                    const isSelected = selectedAssetKey === h.symbol;
                    const isPositive = h.returnVal.startsWith('+');
                    const isNeutral = h.returnVal === '--';
                    return (
                      <tr
                        key={h.symbol}
                        onClick={() => setSelectedAssetKey(h.symbol)}
                        className={`hover:bg-white/[0.03] transition-all cursor-pointer ${
                          isSelected 
                            ? 'bg-indigo-600/10 hover:bg-indigo-600/15 border-l-2 border-indigo-500 font-bold' 
                            : ''
                        }`}
                      >
                        <td className="p-2.5">
                          <span className="text-white font-bold">{h.symbol}</span>
                          <span className="text-[9px] text-white/30 block mt-0.5 font-sans font-normal">{h.name}</span>
                        </td>
                        <td className="p-2.5 text-right text-white/80">{h.qty.toLocaleString()}</td>
                        <td className="p-2.5 text-right text-white/60">${h.avgCost.toFixed(2)}</td>
                        <td className="p-2.5 text-right text-white font-bold">${h.marketPrice.toFixed(2)}</td>
                        <td className={`p-2.5 text-right font-bold ${isNeutral ? 'text-white/40' : isPositive ? 'text-emerald-400' : 'text-pink-400'}`}>
                          {h.returnVal}
                        </td>
                        <td className="p-2.5 text-right text-white font-bold text-indigo-400">
                          {h.weight}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>
          <p className="text-[8.5px] font-mono text-white/20 text-left mt-3 pt-2.5 border-t border-white/5">
            Audit Note: Security values refreshed in synchronization with global Bloomberg real-time feeds.
          </p>
        </div>

        {/* Spotlit Asset Intelligence Card */}
        <div className="lg:col-span-4 text-left">
          <div className="bg-[#080808] border border-indigo-500/15 rounded-xl p-4 flex flex-col justify-between h-full space-y-4">
            <div className="space-y-3.5">
              
              {/* Header Area */}
              <div className="flex items-center justify-between border-b border-white/5 pb-2.5">
                <div>
                  <span className="text-[9px] font-mono text-white/30 uppercase block">Asset Intelligence</span>
                  <h5 className="text-xs font-black text-white font-mono uppercase tracking-wide">
                    {selectedAsset.symbol} - {selectedAsset.name}
                  </h5>
                </div>
                <span className={`px-2 py-0.5 rounded text-[8.5px] font-bold font-mono uppercase border ${
                  selectedAsset.returnPnl >= 0 
                    ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20' 
                    : 'bg-pink-500/10 text-pink-400 border-pink-500/20'
                }`}>
                  {selectedAsset.returnPnl >= 0 ? 'ACCUMULATING' : 'UNDERWEIGHT'}
                </span>
              </div>

              {/* Sub-header interactive tabs */}
              <div className="flex border-b border-white/5 pb-2 text-[10px] font-mono gap-1.5">
                {(['FINANCIALS', 'RISK', 'THESIS'] as const).map((tab) => (
                  <button
                    key={tab}
                    onClick={() => setAssetTab(tab)}
                    className={`px-2.5 py-1 rounded border uppercase tracking-wider text-[8.5px] font-black cursor-pointer transition-all ${
                      assetTab === tab 
                        ? tab === 'FINANCIALS'
                          ? 'bg-emerald-600/20 border-emerald-500/50 text-emerald-400'
                          : 'bg-indigo-600/15 border-indigo-500/50 text-indigo-400' 
                        : tab === 'FINANCIALS'
                          ? 'bg-emerald-500/5 border-emerald-500/10 text-emerald-500/60 hover:text-emerald-400 hover:bg-emerald-500/10'
                          : 'bg-transparent border-transparent text-white/40 hover:text-white/85'
                    }`}
                  >
                    {tab}
                  </button>
                ))}
              </div>

              {/* Tab 1: Financials */}
              {assetTab === 'FINANCIALS' && (() => {
                const renderFinancialCard = (label: string, value: string, textClass: string = 'text-white') => {
                  const info = FINANCIAL_METRICS_INFO[label] || {
                    definition: 'Institutional quantitative metric measuring underlying corporate fundamental performance.',
                    average: 'Varies by industry sector baseline.',
                    alert: 'Active automated terminal rule monitoring.'
                  };
                  return (
                    <div className="bg-black/40 p-2.5 rounded border border-white/5 flex flex-col justify-between relative group overflow-visible cursor-help hover:border-indigo-500/40 hover:bg-indigo-500/[0.02] transition-all min-h-[56px]">
                      <div className="flex justify-between items-start w-full">
                        <span className="text-white/30 text-[8px] uppercase tracking-wider block">{label}</span>
                        <Info className="w-2.5 h-2.5 text-white/20 group-hover:text-indigo-400 transition-colors" />
                      </div>
                      <span className={`${textClass} font-black text-xs mt-1 block`}>{value}</span>

                      {/* Interactive Bloomberg-Style Tooltip */}
                      <div className="absolute bottom-full left-1/2 mb-2.5 -translate-x-1/2 w-64 p-3 bg-zinc-950 border border-indigo-500/30 rounded-lg shadow-2xl opacity-0 group-hover:opacity-100 pointer-events-none transition-all duration-200 z-50 text-left font-sans">
                        <div className="flex items-center gap-1.5 border-b border-white/10 pb-1 mb-1.5">
                          <Info className="w-3.5 h-3.5 text-indigo-400 shrink-0" />
                          <span className="font-mono font-black uppercase tracking-wider text-[9px] text-indigo-300">
                            {label}
                          </span>
                        </div>
                        <p className="text-white/80 text-[10px] leading-relaxed mb-2 font-normal">
                          {info.definition}
                        </p>
                        <div className="bg-[#08080c] rounded p-2 border border-white/5 font-mono text-[9px] space-y-1">
                          <div className="flex justify-between items-center gap-1">
                            <span className="text-white/35 font-semibold uppercase text-[8px] tracking-wider shrink-0">Historical Avg:</span>
                            <span className="text-white font-medium text-[8.5px] text-right">{info.average}</span>
                          </div>
                          <div className="flex justify-between items-center gap-1">
                            <span className="text-white/35 font-semibold uppercase text-[8px] tracking-wider shrink-0">Alert Tier:</span>
                            <span className="text-indigo-400 font-bold text-[8.5px] text-right">{info.alert}</span>
                          </div>
                        </div>
                        <div className="absolute top-full left-1/2 -translate-x-1/2 border-4 border-transparent border-t-zinc-950"></div>
                      </div>
                    </div>
                  );
                };

                return (
                  <div className="space-y-3.5 animate-fadeIn font-mono">
                    <div className="grid grid-cols-2 gap-2 text-[10px]">
                      {renderFinancialCard('Market Cap', selectedAsset.marketCap)}
                      {renderFinancialCard('P/E Ratio', selectedAsset.peRatio)}
                      {renderFinancialCard('P/S Ratio', selectedAsset.psRatio)}
                      {renderFinancialCard('Debt / Equity', selectedAsset.debtEquity)}
                    </div>

                    {/* Profit Margin bar indicator with custom hover tooltip too! */}
                    {selectedAsset.profitMargin !== '--' && (() => {
                      const label = 'Profit Margin';
                      const info = FINANCIAL_METRICS_INFO[label];
                      return (
                        <div className="bg-[#0b0b0f] p-3 rounded-lg border border-white/5 space-y-1.5 relative group overflow-visible cursor-help hover:border-indigo-500/40 hover:bg-indigo-500/[0.02] transition-all">
                          <div className="flex justify-between items-center text-[9px]">
                            <div className="flex items-center gap-1">
                              <span className="text-white/45 uppercase">PROFIT MARGIN:</span>
                              <Info className="w-2.5 h-2.5 text-white/20 group-hover:text-indigo-400 transition-colors" />
                            </div>
                            <span className="text-emerald-400 font-bold">{selectedAsset.profitMargin}</span>
                          </div>
                          <div className="h-1.5 bg-white/5 rounded-full overflow-hidden">
                            <div 
                              style={{ width: selectedAsset.profitMargin }}
                              className="h-full bg-emerald-500/50"
                            ></div>
                          </div>

                          {/* Interactive Bloomberg-Style Tooltip */}
                          <div className="absolute bottom-full left-1/2 mb-2.5 -translate-x-1/2 w-64 p-3 bg-zinc-950 border border-indigo-500/30 rounded-lg shadow-2xl opacity-0 group-hover:opacity-100 pointer-events-none transition-all duration-200 z-50 text-left font-sans">
                            <div className="flex items-center gap-1.5 border-b border-white/10 pb-1 mb-1.5">
                              <Info className="w-3.5 h-3.5 text-indigo-400 shrink-0" />
                              <span className="font-mono font-black uppercase tracking-wider text-[9px] text-indigo-300">
                                {label}
                              </span>
                            </div>
                            <p className="text-white/80 text-[10px] leading-relaxed mb-2 font-normal">
                              {info.definition}
                            </p>
                            <div className="bg-[#08080c] rounded p-2 border border-white/5 font-mono text-[9px] space-y-1">
                              <div className="flex justify-between items-center gap-1">
                                <span className="text-white/35 font-semibold uppercase text-[8px] tracking-wider shrink-0">Historical Avg:</span>
                                <span className="text-white font-medium text-[8.5px] text-right">{info.average}</span>
                              </div>
                              <div className="flex justify-between items-center gap-1">
                                <span className="text-white/35 font-semibold uppercase text-[8px] tracking-wider shrink-0">Alert Tier:</span>
                                <span className="text-indigo-400 font-bold text-[8.5px] text-right">{info.alert}</span>
                              </div>
                            </div>
                            <div className="absolute top-full left-1/2 -translate-x-1/2 border-4 border-transparent border-t-zinc-950"></div>
                          </div>
                        </div>
                      );
                    })()}

                    <div className="grid grid-cols-2 gap-2 text-[10px]">
                      {renderFinancialCard('Beta', selectedAsset.beta, 'text-indigo-400')}
                      {renderFinancialCard('EPS (LTM)', selectedAsset.eps)}
                    </div>
                  </div>
                );
              })()}

              {/* Tab 2: Allocation & Risk */}
              {assetTab === 'RISK' && (
                <div className="space-y-3.5 animate-fadeIn">
                  <div className="bg-black/40 border border-white/5 p-3 rounded-lg space-y-2.5">
                    <div className="flex items-center justify-between">
                      <span className="text-[9.5px] font-mono text-white/40 uppercase">RETURN CONTRIBUTED</span>
                      <span className={`text-xs font-black font-mono ${selectedAsset.returnPnl >= 0 ? 'text-emerald-400' : 'text-pink-400'}`}>
                        {selectedAsset.returnPnl >= 0 ? '+' : ''}${selectedAsset.returnPnl.toLocaleString()}
                      </span>
                    </div>
                    <div className="flex items-center justify-between text-[10px] border-t border-white/5 pt-2">
                      <span className="text-white/40">Portfolio Weight:</span>
                      <strong className="text-indigo-400 text-xs font-black">
                        {selectedAsset.weight}
                      </strong>
                    </div>
                    <div className="flex items-center justify-between text-[10px]">
                      <span className="text-white/40">Dividend Yield:</span>
                      <span className="text-white font-bold">{selectedAsset.dividend}</span>
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-2 text-[10px] font-mono">
                    <div className="bg-[#0b0b0f] p-2.5 rounded border border-white/5">
                      <span className="text-white/30 block text-[8px] uppercase tracking-wider mb-0.5">Volatility</span>
                      <span className="text-white font-bold">{selectedAsset.volatility}</span>
                    </div>
                    <div className="bg-[#0b0b0f] p-2.5 rounded border border-white/5">
                      <span className="text-white/30 block text-[8px] uppercase tracking-wider mb-0.5">Risk Contribution</span>
                      <span className="text-indigo-400 font-bold">{selectedAsset.riskContrib}</span>
                    </div>
                    <div className="bg-[#0b0b0f] p-2.5 rounded border border-white/5">
                      <span className="text-white/30 block text-[8px] uppercase tracking-wider mb-0.5">52-Week Range</span>
                      <span className="text-white font-bold">{selectedAsset.fiftyTwoWeek}</span>
                    </div>
                    <div className="bg-[#0b0b0f] p-2.5 rounded border border-white/5">
                      <span className="text-white/30 block text-[8px] uppercase tracking-wider mb-0.5">Consensus Grade</span>
                      <span className="text-emerald-400 font-bold">{selectedAsset.consensus}</span>
                    </div>
                  </div>
                </div>
              )}

              {/* Tab 3: Thesis & Narrative */}
              {assetTab === 'THESIS' && (
                <div className="space-y-3.5 animate-fadeIn">
                  <div className="space-y-1.5">
                    <span className="text-[8.5px] font-mono text-white/30 uppercase block">Structural Drivers</span>
                    <div className="flex flex-wrap gap-1">
                      {selectedAsset.drivers.map((driver, i) => (
                        <span 
                          key={i} 
                          className="px-1.5 py-0.5 rounded bg-indigo-500/5 border border-indigo-500/10 text-[8.5px] font-mono font-bold text-indigo-300"
                        >
                          {driver}
                        </span>
                      ))}
                    </div>
                  </div>

                  <div className="space-y-1.5 bg-white/[0.01] p-3 rounded-lg border border-white/5">
                    <span className="text-[8.5px] font-mono text-white/30 uppercase block">Investment Thesis Narrative</span>
                    <p className="text-[10px] text-white/60 leading-normal font-sans italic">
                      "{selectedAsset.thesis}"
                    </p>
                  </div>
                </div>
              )}

            </div>

            {/* Timestamp footer */}
            <div className="pt-2 border-t border-white/5 flex items-center justify-between text-[8px] font-mono text-white/30">
              <span>LEDGER: ACTIVE</span>
              <span>EXCHANGE: NYSE/NASDAQ</span>
            </div>

          </div>
        </div>

      </div>

      {/* SECTION 6: PORTFOLIO RISK MATRIX & SECTION 7: SCENARIO SIMULATOR */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        
        {/* SECTION 6: PORTFOLIO RISK MATRIX */}
        <div className="bg-[#080808] border border-white/5 rounded-xl p-4 text-left">
          <div className="border-b border-white/5 pb-3 mb-3">
            <h4 className="text-xs font-black text-white uppercase tracking-wider font-mono flex items-center gap-1.5">
              <Scale className="w-4 h-4 text-amber-400" /> Portfolio Risk Matrix
            </h4>
            <p className="text-[10px] text-white/40 font-mono">
              Risk decomposition limits, asset concentrations, and currency indicators.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            {[
              { label: 'Portfolio Beta', val: '1.08', sub: 'Moderate systemic risk', barColor: 'bg-indigo-500' },
              { label: 'Largest Position', val: 'NVDA 16%', sub: 'Nvidia Corp tech concentration', barColor: 'bg-amber-500' },
              { label: 'Top Sector', val: 'Technology 41%', sub: 'Heavy sector dependency', barColor: 'bg-pink-500' },
              { label: 'Cash Buffer', val: '23%', sub: 'Slippage and liquidity reserve', barColor: 'bg-teal-500' },
              { label: 'FX Exposure', val: 'USD 94%', sub: 'Sovereign dollar dominance', barColor: 'bg-indigo-400' },
              { label: 'Stress Buffer', val: 'AAA Rated', sub: 'High liquidity safety compliance', barColor: 'bg-emerald-500' }
            ].map((item, i) => (
              <div key={i} className="bg-white/[0.01] border border-white/5 p-3 rounded-lg space-y-1 font-mono text-left">
                <span className="text-[8px] text-white/30 uppercase block">{item.label}</span>
                <span className="text-sm font-black text-white block">{item.val}</span>
                <span className="text-[8.5px] text-white/40 block leading-normal">{item.sub}</span>
                <div className="h-0.5 w-full bg-white/5 rounded-full mt-1.5 overflow-hidden">
                  <div className={`h-full w-2/3 ${item.barColor}`}></div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* SECTION 7: SCENARIO SIMULATOR */}
        <div className="bg-[#080808] border border-white/5 rounded-xl p-4 text-left">
          <div className="border-b border-white/5 pb-3 mb-3">
            <h4 className="text-xs font-black text-white uppercase tracking-wider font-mono flex items-center gap-1.5">
              <Zap className="w-4 h-4 text-red-400" /> Scenario Simulator
            </h4>
            <p className="text-[10px] text-white/40 font-mono">
              Hypothetical macro events applied dynamically against the active portfolio value.
            </p>
          </div>

          <div className="space-y-3">
            {[
              {
                title: 'If S&P 500 falls 10%',
                impact: 'Estimated Loss: -$6,830',
                isPositive: false,
                percent: '-6.8%'
              },
              {
                title: 'If Technology rises 15%',
                impact: 'Estimated Gain: +$4,100',
                isPositive: true,
                percent: '+4.1%'
              },
              {
                title: 'If USD weakens 10%',
                impact: 'Estimated Impact: +$1,250',
                isPositive: true,
                percent: '+1.2%'
              }
            ].map((sc, i) => (
              <div key={i} className="flex items-center justify-between p-3 rounded-lg bg-white/[0.01] border border-white/5 font-mono text-[10px]">
                <div className="space-y-0.5">
                  <span className="text-white font-bold block">{sc.title}</span>
                  <span className="text-white/45 block">{sc.impact}</span>
                </div>
                <div className={`px-2 py-1 rounded text-[10px] font-bold ${
                  sc.isPositive 
                    ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/25' 
                    : 'bg-pink-500/10 text-pink-400 border border-pink-500/25'
                }`}>
                  {sc.percent}
                </div>
              </div>
            ))}
          </div>
        </div>

      </div>

      {/* SECTION 8: RESEARCH FEED */}
      <div className="bg-[#080808] border border-white/5 rounded-xl p-4 text-left">
        <div className="border-b border-white/5 pb-3 mb-3">
          <h4 className="text-xs font-black text-white uppercase tracking-wider font-mono flex items-center gap-1.5">
            <BookOpen className="w-4 h-4 text-indigo-400" /> Real-Time Research Feed
          </h4>
          <p className="text-[10px] text-white/40 font-mono">
            Key macroeconomic alerts and algorithmic observations impacting the tokenized landscape.
          </p>
        </div>

        {/* Scrollable grid layout */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3.5 pt-1">
          {[
            {
              asset: 'AAPL',
              body: 'Services revenue reaches record highs. Subscription upgrades provide cash compounding resilience.',
              source: 'Bloomberg Research'
            },
            {
              asset: 'NVDA',
              body: 'AI infrastructure spending accelerates worldwide. Institutional accumulation remains heavily focused on next-gen silicon pipelines.',
              source: 'Stripe Analyst Feed'
            },
            {
              asset: 'SPY',
              body: 'Federal Reserve maintains restrictive interest rates. Yield capture parameters remain elevated.',
              source: 'Sovereign Macro'
            },
            {
              asset: 'MSFT',
              body: 'Enterprise cloud margins exceed expectations. Azure integration of large language engines continues scaling.',
              source: 'Intelligence Desk'
            }
          ].map((feed, i) => (
            <div key={i} className="bg-white/[0.01] border border-white/5 p-3 rounded-lg flex flex-col justify-between space-y-3 font-mono text-left">
              <div className="space-y-1.5">
                <div className="flex items-center justify-between">
                  <span className="text-[9.5px] font-black text-white bg-indigo-500/10 px-1.5 py-0.2 rounded border border-indigo-500/25">
                    {feed.asset}
                  </span>
                  <span className="text-[8px] text-white/20 uppercase font-bold">{feed.source}</span>
                </div>
                <p className="text-[10px] text-white/60 leading-normal font-sans italic">
                  "{feed.body}"
                </p>
              </div>
              <span className="text-[8px] text-emerald-400 font-bold uppercase tracking-wide">
                ● TIER-1 INSIGHT CLEARED
              </span>
            </div>
          ))}
        </div>
      </div>

    </div>
  );
}
